CREATE TABLE cart
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_uuid UUID                                    NOT NULL,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE cart_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INT                                     NOT NULL,
    CONSTRAINT pk_cart_item PRIMARY KEY (id)
);

CREATE TABLE product
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                    VARCHAR(255)                            NOT NULL,
    stock                   INT                                     NOT NULL,
    price                   INT                                     NOT NULL,
    description             VARCHAR(255),
    created_date_time       TIMESTAMP,
    last_modified_date_time TIMESTAMP,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE user_account
(
    uuid                    UUID         NOT NULL,
    username                VARCHAR(255) NOT NULL,
    password                VARCHAR(255) NOT NULL,
    email                   VARCHAR(255) NOT NULL,
    phone_number            VARCHAR(255) NOT NULL,
    role                    VARCHAR(255) NOT NULL,
    created_date_time       TIMESTAMP,
    last_modified_date_time TIMESTAMP,
    CONSTRAINT pk_user_account PRIMARY KEY (uuid)
);

ALTER TABLE cart_item
    ADD CONSTRAINT uc_82427a8c58abc7d86698414b4 UNIQUE (cart_id, product_id);

ALTER TABLE cart
    ADD CONSTRAINT uc_cart_user_uuid UNIQUE (user_uuid);

ALTER TABLE user_account
    ADD CONSTRAINT uc_user_account_email UNIQUE (email);

ALTER TABLE user_account
    ADD CONSTRAINT uc_user_account_phonenumber UNIQUE (phone_number);

ALTER TABLE user_account
    ADD CONSTRAINT uc_user_account_username UNIQUE (username);

ALTER TABLE cart_item
    ADD CONSTRAINT FK_CART_ITEM_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE cart_item
    ADD CONSTRAINT FK_CART_ITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE cart
    ADD CONSTRAINT FK_CART_ON_USER_UUID FOREIGN KEY (user_uuid) REFERENCES user_account (uuid);